### ISSUE TITLE
Strings Sampler 1&2 not working

### ISSUE THREAD

**Issue by Vollblut** [willismichael/virtual-playing-orchestra-ardour-template#3]
I checked all the paths in the .sfz files, seems correct, but there's nothing coming from it. installed in /opt/ as per instructions. MIDI-Mapping, paths in the *.sfz files are correct, linuxsampler mapping in the template is too. 
All wave files audition just fine and are playable in ncmpcpp etc.

**Comment by michaelwillis** [comment]
@Vollblut sorry I'm so late in this. I think this might not be compatible with the latest virtual playing orchestra. I'm considering making an overhaul to this whole template.

**Comment by michaelwillis** [comment]
The latest version of this template uses sfizz instead of LinuxSampler, so this issue is obsolete.
